version: '3'
services:
  mysql:
    image: mysql
    container_name: mysql-user-management
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: user_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: "@passw0rd"
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    restart: always
    networks:
      - user-management

volumes:
  mysql_data:

networks:
  user-management:
    driver: bridge