version: '3'
services:
  mysql:
    image: mysql
    container_name: user_service_mysql
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_DATABASE: user_service
      MYSQL_USER: admin
      MYSQL_PASSWORD: "@passw0rd"
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
      - ./metaData/sql/ddl.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./metaData/sql/dml.sql:/docker-entrypoint-initdb.d/2-data.sql
    restart: always
    networks:
      - user_service_network
volumes:
  mysql_data:
  esdata:
    driver: local

networks:
  user_service_network:
    driver: bridge