spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?useSSL=false
    username: admin
    password: '@passw0rd'
    driver-class-name: com.mysql.jdbc.Driver