spring:
  security:
    oauth2:
      client:
        clientId: 233668646673605
        clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
        accessTokenUri: https://graph.facebook.com/oauth/access_token
        userAuthorizationUri: https://www.facebook.com/dialog/oauth
        tokenName: oauth_token
        authenticationScheme: query
        clientAuthenticationScheme: form
      resource:
        userInfoUri: https://graph.facebook.com/me
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/user_management?useSSL=false
    username: admin
    password: '@passw0rd'
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:/mysql/ddl.sql
    data: classpath:/mysql/dml.sql