-- MySQL Script generated by MySQL Workbench
-- Sat Jan 13 09:33:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema user_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema user_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `user_service`
  DEFAULT CHARACTER SET utf8;
USE `user_service`;

-- -----------------------------------------------------
-- Table `user_service`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_service`.`users` (
  `user_id`       INT(11)     NOT NULL AUTO_INCREMENT,
  `first_name`    VARCHAR(45) NOT NULL,
  `last_name`     VARCHAR(45) NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `user_name`     VARCHAR(45) NOT NULL,
  `password`      VARCHAR(45) NOT NULL,
  `created_time`  TIMESTAMP   NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_time`  DATETIME    NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 1001
  DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `user_service`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_service`.`address` (
  `address_id`      INT(11)     NOT NULL AUTO_INCREMENT,
  `city`            VARCHAR(45) NOT NULL,
  `country`         VARCHAR(45) NOT NULL,
  `zipcode`         INT(11)     NOT NULL,
  `primary_address` TINYINT(4)  NOT NULL DEFAULT '1',
  `address_desc`    VARCHAR(45) NOT NULL COMMENT 'Description about the address Eg: Home, Work, etc',
  `user_id`         INT(11)     NOT NULL,
  PRIMARY KEY (`address_id`, `user_id`),
  INDEX `fk_address_customer_idx` (`user_id` ASC),
  CONSTRAINT `fk_address_customer`
  FOREIGN KEY (`user_id`)
  REFERENCES `user_service`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
